FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY . .
RUN dotnet restore Tjip.Havik.Huizenvergelijker.Api/Tjip.Havik.Huizenvergelijker.Api.csproj

WORKDIR /src/Tjip.Havik.Huizenvergelijker.Api
RUN dotnet build Tjip.Havik.Huizenvergelijker.Api.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Tjip.Havik.Huizenvergelijker.Api.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Tjip.Havik.Huizenvergelijker.Api.dll"]